CREATE TABLE resources (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
type VARCHAR(30) NOT NULL,
size INT NOT NULL,
content MEDIUMBLOB NOT NULL,
editor VARCHAR(15) NOT NULL,
edit_time TIMESTAMP NOT NULL,
PRIMARY KEY(id)
);